project: coconut
save_path: checkpoints/prosqa_looplm
name: prosqa-looplm

only_eval: False

coconut: False
cot: False
no_thoughts: True
no_cot: True

looplm: True
n_loop: 4

c_thought: 0
epochs_per_stage: 5
max_latent_stage: 6
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/prosqa_train.json
val_path: data/prosqa_valid.json
reset_optimizer: True
batch_size_training: 16
debug: False
gradient_accumulation_steps: 2
num_epochs: 50
lr: !!float "1e-4"
weight_decay: 0.01
use_local_model: False